/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/Teou5fCDMN2
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Libre_Franklin } from 'next/font/google'
import { Rubik } from 'next/font/google'

libre_franklin({
  subsets: ['latin'],
  display: 'swap',
})

rubik({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import { Input } from "@/components/ui/input"
import { Button } from "@/components/ui/button"

export function Hero() {
  return (
    <section className="w-full py-2 md:py-24 lg:py-10 xl:py-15">
      <div className="container px-2 md:px-3">
        <div className="grid gap-6 lg:grid-cols-[1fr_1fr] lg:gap-12 xl:grid-cols-[1fr_1fr]">
          <div className="flex flex-col justify-center space-y-4">
            <div className="space-y-2">
              <h1 className="text-4xl font-bold tracking-tighter sm:text-5xl md:text-6xl lg:text-7xl">
                Unlock the Power of Web Development
              </h1>
              <p className="max-w-[600px] text-muted-foreground md:text-xl lg:text-lg xl:text-xl">
                Discover our cutting-edge tools and resources to build exceptional web experiences. Join our community
                of innovators and take your projects to new heights.
              </p>
            </div>
            <div className="w-full max-w-sm space-y-2">
              <form className="flex gap-2">
                <Input type="email" placeholder="Enter your email" className="max-w-lg flex-1" />
                <Button type="submit" className="whitespace-nowrap">
                  Get Started
                </Button>
              </form>
              <p className="text-xs text-muted-foreground">
                Sign up to unlock exclusive features and stay ahead of the curve.
              </p>
            </div>
          </div>
          <img
            src="/placeholder.svg"
            width="350"
            alt="Hero"
            className="mx-auto overflow-hidden rounded-xl sm:w-full"
          />
        </div>
      </div>
    </section>
  )
}
