/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/8OYaGsGBUR1
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import { Card, CardHeader, CardTitle, CardDescription, CardContent } from "@/components/ui/card"
import { Label } from "@/components/ui/label"
import { Input } from "@/components/ui/input"
import { Button } from "@/components/ui/button"

export function OrderForm() {
  return (
    <Card>
      <CardHeader>
        <CardTitle>Order Lookup</CardTitle>
        <CardDescription>Enter an Order ID and Product Name to view order details.</CardDescription>
      </CardHeader>
      <CardContent>
        <form className="grid gap-4">
          <div className="grid gap-2">
            <Label htmlFor="orderId">Order ID</Label>
            <Input id="orderId" placeholder="Enter Order ID" />
          </div>
          <div className="grid gap-2">
            <Label htmlFor="product">Product Name</Label>
            <Input id="product" placeholder="Enter Product Name" />
          </div>
          <Button type="submit" className="mt-4">
            Submit
          </Button>
        </form>
      </CardContent>
    </Card>
  )
}
